// skills/fingerprint-nextjs/snippets/provider.tsx
// app/fingerprint-provider.tsx — a 'use client' wrapper around FingerprintProvider.
// The provider needs to run in the browser, so it can't live directly in the server-rendered
// layout. Region MUST match your workspace ('us' | 'eu' | 'ap') or identification fails with
// "API key not found" — read both values from NEXT_PUBLIC_ env vars, don't hardcode.
'use client'

import { FingerprintProvider } from '@fingerprint/react'

export function FingerprintClientProvider({ children }: { children: React.ReactNode }) {
  return (
    <FingerprintProvider
      apiKey={process.env.NEXT_PUBLIC_FINGERPRINT_PUBLIC_API_KEY!}
      region={process.env.NEXT_PUBLIC_FINGERPRINT_REGION as 'us' | 'eu' | 'ap'}
    >
      {children}
    </FingerprintProvider>
  )
}

// skills/fingerprint-svelte/snippets/Provider.svelte
<!-- Mount once at the app root (e.g. src/App.svelte, or +layout.svelte in SvelteKit).
     The region MUST match your workspace ('us' | 'eu' | 'ap') or identification fails with
     "API key not found" — read it from env, don't hardcode it.
     The Svelte provider takes a single `options` prop (apiKey + region). -->
<script>
  import { FingerprintProvider } from '@fingerprint/svelte'
  import Identify from './use-visitor-data.svelte'

  const options = {
    apiKey: import.meta.env.VITE_FINGERPRINT_PUBLIC_API_KEY,
    region: import.meta.env.VITE_FINGERPRINT_REGION,
  }
</script>

<FingerprintProvider {options}>
  <Identify />
</FingerprintProvider>
